name: CI Pipeline

# Run on push or pull request to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run lint
      - name: Lint
        run: npm run lint

      # Step 5: Build frontend
      - name: Build frontend
        run: cd apps/frontend && npm run build

      # Step 6: Build backend (optional if you want to test)
      - name: Build backend
        run: cd apps/backend && echo "No build step yet"
